### ISSUE TITLE
SystemHeatFissionReactors.cfg isn't applied

### ISSUE THREAD

**Issue by gotmachine** [judicator/KerbalismSystemHeat#1]
The patch isn't applied due its AFTER pass being too early : 
https://github.com/judicator/KerbalismSystemHeat/blob/64766ccc00a16b9ae13a218ede236a4d9788cf4c/GameData/zKerbalismSystemHeat/Patches/SystemHeatFissionReactors.cfg#L1

Changing `AFTER[SystemHeat]` to `AFTER[zzzz_SystemHeat]` solved it

**Comment by judicator** [comment]
Thanks!
Fixed in 0.4 release.
